(function(){
  'use strict';
  const CONFIG={executionPlaneEnabled:false,dashboardUiEnabled:true,storageKey:'studio-os.ai-workforce.v1',schemaVersion:'1.0.0'};
  const TASK_STATES=Object.freeze(['Queued','Running','Waiting','Blocked','Completed','Failed','Cancelled']);
  const TEAMS=['Executive','Development','Business','Marketing','Automation','Monitoring'];
  const seedAgents=[
    ['ceo','CEO Agent','Executive','Chief Executive Orchestrator',['Strategy','Planning','Governance'],['Workflow Engine','Policy Guard']],
    ['architect','Architect','Development','Solution architecture',['Architecture','Scalability'],['Filesystem','Context7']],
    ['developer','Developer','Development','Software delivery',['Engineering','APIs'],['GitHub','Codex']],
    ['qa','QA','Development','Quality assurance',['Testing','Regression'],['Playwright','GitHub']],
    ['security','Security','Development','Security assurance',['Threat modeling','RBAC'],['GitHub','Filesystem']],
    ['devops','DevOps','Development','Delivery operations',['CI/CD','Containers'],['Vercel','Docker']],
    ['product-owner','Product Owner','Business','Product direction',['Roadmaps','Value'],['Notion','Airtable']],
    ['project-manager','Project Manager','Business','Delivery coordination',['Planning','Risk'],['Notion','Google Calendar']],
    ['finance','Finance','Business','Cost governance',['Budgeting','Forecasting'],['Airtable']],
    ['data-analyst','Data Analyst','Business','Decision intelligence',['Analytics','KPIs'],['Supabase','Airtable']],
    ['research','Research','Business','Evidence gathering',['Research','Synthesis'],['Google Drive','Context7']],
    ['seo','SEO','Marketing','Search optimization',['SEO','Keywords'],['Google Drive']],
    ['etsy','Etsy','Marketing','Marketplace operations',['Listings','Conversion'],['Etsy']],
    ['pinterest','Pinterest','Marketing','Visual discovery',['Trends','Campaigns'],['Pinterest']],
    ['shopify','Shopify','Marketing','Commerce operations',['Catalog','Conversion'],['Shopify']],
    ['social','Social Media','Marketing','Channel operations',['Engagement','Scheduling'],['Google Drive']],
    ['content','Content','Marketing','Content production',['Copy','Editorial'],['Notion','Google Drive']],
    ['github-auto','GitHub Automation','Automation','Repository automation',['CI','Pull requests'],['GitHub']],
    ['notion-auto','Notion Automation','Automation','Knowledge automation',['Knowledge','Sync'],['Notion']],
    ['drive-auto','Drive Automation','Automation','File automation',['Files','Sync'],['Google Drive']],
    ['airtable-auto','Airtable Automation','Automation','Data automation',['Records','Sync'],['Airtable']],
    ['vercel-auto','Vercel Automation','Automation','Deployment automation',['Deployments','Observability'],['Vercel']],
    ['mcp-services','MCP Services','Automation','Tool gateway',['MCP','Registry'],['MCP']],
    ['monitor','Monitoring Agent','Monitoring','Operational monitoring',['Telemetry','Incidents'],['Supabase','Vercel']]
  ].map(a=>({id:a[0],name:a[1],team:a[2],role:a[3],expertise:a[4],tools:a[5],provider:'Unbound',status:'offline',systemPrompt:`Operate as the ${a[1]} within Studio OS. Respect execution policy, approval boundaries, least privilege and auditable output.`,createdAt:'2026-07-11T00:00:00Z'}));
  const navItems=[['command','⌘','Command Center'],['agents','◎','Agents'],['workflows','⌁','Workflows'],['tasks','☷','Tasks'],['approvals','✓','Approvals'],['audit','≡','Audit'],['tools','◇','Tools'],['monitoring','◴','Monitoring'],['settings','⚙','Settings']];
  const workflowTypes=['Start','Decision','Approval','Loop','Condition','Parallel','Retry','Error handler','Timeout','Webhook','Human approval'];
  let state=loadState(),route='command',selected='ceo',search='';
  const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  function loadState(){try{const raw=localStorage.getItem(CONFIG.storageKey);if(!raw)return fresh();const saved=JSON.parse(raw);return {...fresh(),...saved,agents:mergeAgents(saved.agents||[])};}catch(e){console.warn('[Studio OS] State recovery:',e);return fresh();}}
  function fresh(){return{schemaVersion:CONFIG.schemaVersion,agents:seedAgents,tasks:[],workflows:[],approvals:[],audit:[auditEvent('configuration.loaded','system','Studio OS configuration loaded')],settings:{role:'Administrator',telemetryRefresh:15}}}
  function mergeAgents(custom){const map=new Map(seedAgents.map(a=>[a.id,a]));custom.forEach(a=>map.set(a.id,a));return[...map.values()]}
  function save(){try{localStorage.setItem(CONFIG.storageKey,JSON.stringify(state));}catch(e){toast('Opslaan mislukt: lokale opslag niet beschikbaar','error');}}
  function auditEvent(action,actor,summary,metadata={}){return{id:crypto.randomUUID?.()||Date.now().toString(36),timestamp:new Date().toISOString(),action,actor,summary,metadata}}
  function audit(action,summary,metadata={}){state.audit.unshift(auditEvent(action,'local-user',summary,metadata));save()}
  function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');clearTimeout(el._timer);el._timer=setTimeout(()=>el.classList.remove('show'),2600)}
  function renderNav(){$('#nav').innerHTML=navItems.map(n=>`<button class="nav-btn ${route===n[0]?'active':''}" data-route="${n[0]}"><span class="nav-icon">${n[1]}</span>${n[2]}</button>`).join('')}
  function navigate(next){route=next;renderNav();render();$('.sidebar').classList.remove('open')}
  function render(){const item=navItems.find(n=>n[0]===route);$('#pageTitle').textContent=item[2];$('#pageSubtitle').textContent=route==='command'?'NumberNinjaDesigns · Studio OS':'NumberNinjaDesigns · AI Workforce';const views={command:commandView,agents:agentsView,workflows:workflowsView,tasks:tasksView,approvals:approvalsView,audit:auditView,tools:toolsView,monitoring:monitoringView,settings:settingsView};$('#workspace').innerHTML=views[route]();bindView()}
  function kpi(label,value,suffix='',na=false){return`<div class="kpi"><label>${label}</label><strong class="${na?'na':''}">${value}<small>${suffix}</small></strong></div>`}
  function commandView(){return`<div class="kpi-grid">${kpi('AGENTS REGISTERED',state.agents.length)}${kpi('TASKS RUNNING',state.tasks.filter(t=>t.status==='Running').length)}${kpi('DAILY COST','—','provider telemetry',true)}${kpi('SUCCESS RATE','—','no executions',true)}${kpi('PENDING APPROVALS',state.approvals.filter(a=>a.status==='Waiting').length)}</div>${organizationView()}<div class="command-grid"><section class="panel network-panel"><div class="panel-head"><h2>AGENT NETWORK TOPOLOGY</h2><span>Interactive · configuration view</span></div>${network()}</section>${inspector()}</div><div class="lower-grid">${taskPanel()}${eventPanel()}</div>`}
  function organizationView(){return`<section class="panel org-panel" aria-labelledby="organizationTitle"><div class="panel-head"><h2 id="organizationTitle">ORGANIZATION ARCHITECTURE</h2><span>One brand · two production lines · one control plane</span></div><div class="org-chart"><a class="org-node org-root" href="../../index.html"><strong>NumberNinjaDesigns</strong><small>Master brand and commercial identity</small></a><div class="org-branches" aria-label="Production divisions"><a class="org-node" href="../listing-intelligence-engine/dashboard/index.html"><strong>Digital Production</strong><small>Templates, intelligence and digital listings</small></a><a class="org-node" href="../../designs.html"><strong>Physical Production</strong><small>Apparel, artwork and product previews</small></a></div><button class="org-node org-control" type="button" data-route="agents"><strong>Studio OS</strong><small>Shared governance, agents and automation</small></button></div></section>`}
  function network(){const teams=TEAMS.filter(t=>t!=='Executive'),cx=410,cy=230,r=175;let edges='',nodes='';teams.forEach((team,i)=>{const a=(Math.PI*2*i/teams.length)-Math.PI/2,x=cx+Math.cos(a)*r,y=cy+Math.sin(a)*r;edges+=`<line class="edge ${i===1?'active':''}" x1="${cx}" y1="${cy}" x2="${x}" y2="${y}"/>`;nodes+=nodeSvg(team.toLowerCase(),team,x,y,34,'team',state.agents.filter(n=>n.team===team).length+' agents')});nodes+=nodeSvg('ceo','CEO Agent',cx,cy,44,'team','orchestrator');return`<div class="network-wrap"><svg viewBox="0 0 820 460" role="img" aria-label="Netwerk van agentteams rond de CEO Agent">${edges}${nodes}</svg><div class="legend"><span>━━ active flow</span><span>┄ configured link</span><span>● registered agent</span></div></div>`}
  function nodeSvg(id,name,x,y,size,cls,sub){return`<g class="node ${cls} ${selected===id?'selected':''}" data-agent="${id}" transform="translate(${x} ${y})"><circle r="${size}"/><circle class="online" r="3" cx="${size-5}" cy="-${size-5}"/><text y="-2">${esc(name)}</text><text class="sub" y="13">${esc(sub)}</text></g>`}
  function selectedAgent(){return state.agents.find(a=>a.id===selected)||state.agents.find(a=>a.team===selected)||state.agents[0]}
  function inspector(){const a=selectedAgent();return`<aside class="panel inspector"><div class="panel-head"><h2>AGENT INSPECTOR</h2><span>${esc(a.id)}</span></div><div class="inspector-body"><div class="agent-title"><div class="avatar">AI</div><div><h3>${esc(a.name)}</h3><span class="online-text">● ${a.status.toUpperCase()}</span></div></div><dl class="definition-list"><dt>Role</dt><dd>${esc(a.role)}</dd><dt>Team</dt><dd>${esc(a.team)}</dd><dt>Provider</dt><dd>${esc(a.provider)}</dd><dt>Last activity</dt><dd>Geen runtime telemetry</dd></dl><div class="section-label">EXPERTISE</div><div class="tags">${a.expertise.map(x=>`<span class="tag">${esc(x)}</span>`).join('')}</div><div class="section-label">TOOLS / MCP</div><div class="tags">${a.tools.map(x=>`<span class="tag">${esc(x)}</span>`).join('')}</div><div class="section-label">SYSTEM PROMPT</div><p style="color:var(--muted);font-size:9px;line-height:1.6">${esc(a.systemPrompt)}</p><div class="agent-actions"><button class="btn primary" data-disabled-action="start">Start</button><button class="btn secondary" data-disabled-action="stop">Stop</button><button class="btn secondary" data-route="agents">Profiel</button></div></div></aside>`}
  function taskPanel(){return`<section class="panel"><div class="panel-head"><h2>EXECUTION / TASK QUEUE</h2><button class="btn secondary" data-action="new-task">Nieuwe taak</button></div><div class="table-wrap">${state.tasks.length?table(['Taak','Agent','Status','Prioriteit'],state.tasks.slice(0,8).map(t=>[esc(t.title),esc(t.agentName),status(t.status),esc(t.priority)])):`<div class="empty"><span><b>Geen taken in de wachtrij</b>Maak een taak aan om de lokale planningsflow te starten.</span></div>`}</div></section>`}
  function eventPanel(){return`<section class="panel"><div class="panel-head"><h2>AUDIT EVENT STREAM</h2><span>immutable local trail</span></div><div class="table-wrap">${table(['Tijd','Actor','Event'],state.audit.slice(0,8).map(e=>[new Date(e.timestamp).toLocaleTimeString('nl-NL'),esc(e.actor),esc(e.summary)]))}</div></section>`}
  function pageHead(title,desc,action=''){return`<div class="page-head"><div><h2>${title}</h2><p>${desc}</p></div>${action}</div>`}
  function agentsView(){const filtered=state.agents.filter(a=>(a.name+' '+a.role+' '+a.team).toLowerCase().includes(search));return`${pageHead('Agent Registry','Definities, capabilities en governancebindingen.',`<button class="btn primary" data-action="add-agent">+ Agent registreren</button>`)}<div class="cards">${filtered.map(a=>`<article class="agent-card" data-agent-card="${a.id}"><header><h3>${esc(a.name)}</h3><span class="state ${a.status}">${a.status}</span></header><p>${esc(a.role)}</p><div class="tags"><span class="tag">${esc(a.team)}</span>${a.tools.slice(0,2).map(t=>`<span class="tag">${esc(t)}</span>`).join('')}</div></article>`).join('')}</div>`}
  function workflowsView(){return`${pageHead('Workflow Engine','Drag nodes naar het canvas. Opslaan registreert een definitie; uitvoeren vereist de execution plane.',`<div class="toolbar"><button class="btn secondary" data-action="clear-workflow">Wissen</button><button class="btn primary" data-action="save-workflow">Workflow opslaan</button></div>`)}<div class="workflow-layout"><aside class="node-palette"><h3>Nodes</h3>${workflowTypes.map((x,i)=>`<div class="palette-item" draggable="true" data-node-type="${esc(x)}">${esc(x)}</div>`).join('')}</aside><div class="workflow-canvas" id="workflowCanvas" aria-label="Workflow canvas"></div><aside class="properties"><h3>Properties</h3><p style="color:var(--muted);line-height:1.6">Selecteer of sleep een node. De editor ondersteunt start, decisions, approvals, loops, conditions, parallel execution, retries, error handling, timeouts en webhooks.</p><div class="section-label">EXECUTION</div><button class="btn primary" disabled title="Execution plane is uitgeschakeld">Start workflow</button></aside></div>`}
  function tasksView(){return`${pageHead('Task Queues','Queuebeheer voor alle geregistreerde agents.',`<button class="btn primary" data-action="new-task">+ Taak</button>`)}<section class="panel"><div class="table-wrap">${state.tasks.length?table(['Taak','Agent','Status','Prioriteit','Aangemaakt'],state.tasks.map(t=>[esc(t.title),esc(t.agentName),status(t.status),esc(t.priority),new Date(t.createdAt).toLocaleString('nl-NL')])):`<div class="empty"><span><b>Geen taken</b>De queue is leeg.</span></div>`}</div></section>`}
  function approvalsView(){return`${pageHead('Approval Center','Menselijke beslissingen met volledige auditregistratie.')}<section class="panel"><div class="table-wrap">${state.approvals.length?table(['Verzoek','Risico','Status','Acties'],state.approvals.map(a=>[esc(a.title),esc(a.risk),status(a.status),`<button class="btn secondary" data-approve="${a.id}">Goedkeuren</button>`])):`<div class="empty"><span><b>Geen openstaande approvals</b>Er zijn geen acties die menselijke goedkeuring vereisen.</span></div>`}</div></section>`}
  function auditView(){return`${pageHead('Audit Trail','Prompts, responses, tool/API/MCP-calls, runtime, kosten, tokens, errors en retries worden via het eventcontract geprojecteerd.',`<button class="btn secondary" data-action="export">Export JSON</button>`)}<section class="panel"><div class="table-wrap" style="max-height:calc(100vh - 170px)">${table(['Timestamp','Actor','Action','Samenvatting'],state.audit.map(e=>[esc(e.timestamp),esc(e.actor),esc(e.action),esc(e.summary)]))}</div></section>`}
  function toolsView(){const tools=['OpenAI','GitHub','Notion','Google Drive','Google Calendar','Gmail','Airtable','Shopify','Etsy','Printify','Vercel','Supabase','Docker','Filesystem','Playwright','Context7','Claude Code','Codex','MCP'];return`${pageHead('Tool Registry','Manifest-gestuurde adapters; nieuwe tools vereisen geen UI-codewijziging.')}<div class="cards">${tools.map(t=>`<article class="agent-card"><header><h3>${t}</h3><span class="state queued">unbound</span></header><p>Geen actieve credentialbinding. Secrets worden nooit in deze module opgeslagen.</p><button class="btn secondary" data-disabled-action="connect">Configureren</button></article>`).join('')}</div>`}
  function monitoringView(){return`${pageHead('Monitoring','Realtime telemetry wordt beschikbaar zodra een geautoriseerde eventstream-adapter is gekoppeld.')}<div class="kpi-grid">${kpi('AGENTS ONLINE','—','telemetry',true)}${kpi('AVG RUNTIME','—','telemetry',true)}${kpi('MONTHLY COST','—','telemetry',true)}${kpi('FAILURE RATE','—','telemetry',true)}${kpi('API / MCP USAGE','—','telemetry',true)}</div><section class="panel"><div class="empty"><span><b>Telemetry adapter niet gekoppeld</b>De UI verzint geen operationele metrics. Koppel een conform eventstream-endpoint om live data te projecteren.</span></div></section>`}
  function settingsView(){return`${pageHead('Settings','Lokale cockpitvoorkeuren en governancecontext.')}<section class="panel" style="padding:18px;max-width:700px"><div class="form-grid"><label>Actieve rol<select id="roleSetting"><option>Administrator</option><option>Operator</option><option>Approver</option><option>Auditor</option><option>Viewer</option></select></label><label>Telemetry refresh (seconden)<input id="refreshSetting" type="number" min="5" max="300" value="${state.settings.telemetryRefresh}"></label><label class="wide">Execution plane<input value="Uitgeschakeld door config/studio.config.json" disabled></label><label class="wide">Secret management<input value="Externe vault vereist; geen browseropslag" disabled></label></div><div class="dialog-actions"><button class="btn primary" data-action="save-settings">Opslaan</button></div></section>`}
  function table(headers,rows){return`<table class="data-table"><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td>${c}</td>`).join('')}</tr>`).join('')}</tbody></table>`}
  function status(s){const safe=TASK_STATES.includes(s)||s==='Approved'?s:'Blocked';return`<span class="state ${safe.toLowerCase()}">${esc(safe)}</span>`}
  function bindView(){document.querySelectorAll('[data-route]').forEach(b=>b.onclick=()=>navigate(b.dataset.route));document.querySelectorAll('[data-agent]').forEach(n=>n.onclick=()=>{selected=n.dataset.agent;render()});document.querySelectorAll('[data-agent-card]').forEach(n=>n.onclick=()=>{selected=n.dataset.agent;navigate('command')});document.querySelectorAll('[data-disabled-action]').forEach(b=>b.onclick=()=>toast('Actie geblokkeerd: execution plane of credentialbinding is uitgeschakeld.'));document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>action(b.dataset.action));document.querySelectorAll('[data-approve]').forEach(b=>b.onclick=()=>approve(b.dataset.approve));bindWorkflow()}
  function action(name){if(name==='add-agent')return openAgent();if(name==='new-task')return newTask();if(name==='export')return exportAudit();if(name==='save-settings'){state.settings.role=$('#roleSetting').value;state.settings.telemetryRefresh=Number($('#refreshSetting').value);audit('settings.updated','Cockpitinstellingen bijgewerkt');toast('Instellingen opgeslagen')}if(name==='save-workflow')saveWorkflow();if(name==='clear-workflow'){sessionStorage.removeItem('studio-os.workflow.draft');render()} }
  function newTask(){const title=prompt('Taakomschrijving');if(!title)return;const a=selectedAgent();const t={id:crypto.randomUUID?.()||Date.now().toString(36),title:title.slice(0,200),agentId:a.id,agentName:a.name,status:'Queued',priority:'Normal',createdAt:new Date().toISOString()};state.tasks.unshift(t);audit('task.queued',`Taak “${t.title}” lokaal ingepland`,{taskId:t.id,agentId:a.id});render();toast('Taak toegevoegd aan lokale queue')}
  function openAgent(){$('#agentDialog').showModal()}
  function registerAgent(fd){const name=String(fd.get('name')).trim(),id=name.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'')+'-'+Date.now().toString(36);const a={id,name,team:String(fd.get('team')),role:String(fd.get('role')).trim(),provider:String(fd.get('provider')),expertise:String(fd.get('expertise')).split(',').map(x=>x.trim()).filter(Boolean),tools:[],status:'offline',systemPrompt:String(fd.get('systemPrompt')).trim(),createdAt:new Date().toISOString()};state.agents.push(a);audit('agent.registered',`Agent ${a.name} geregistreerd`,{agentId:id});selected=id;render();toast('Agent geregistreerd')}
  function approve(id){const a=state.approvals.find(x=>x.id===id);if(!a)return;a.status='Approved';audit('approval.approved',`Approval ${a.title} goedgekeurd`,{approvalId:id});render()}
  function exportAudit(){const blob=new Blob([JSON.stringify({schemaVersion:CONFIG.schemaVersion,exportedAt:new Date().toISOString(),events:state.audit},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`studio-os-audit-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),0);audit('audit.exported','Audittrail geëxporteerd')}
  function bindWorkflow(){const canvas=$('#workflowCanvas');if(!canvas)return;const draft=JSON.parse(sessionStorage.getItem('studio-os.workflow.draft')||'[]');draft.forEach(renderWfNode);document.querySelectorAll('[draggable]').forEach(el=>el.ondragstart=e=>e.dataTransfer.setData('text/plain',el.dataset.nodeType));canvas.ondragover=e=>e.preventDefault();canvas.ondrop=e=>{e.preventDefault();const rect=canvas.getBoundingClientRect(),node={id:Date.now().toString(36),type:e.dataTransfer.getData('text/plain'),x:Math.max(0,e.clientX-rect.left-80),y:Math.max(0,e.clientY-rect.top-20)};draft.push(node);sessionStorage.setItem('studio-os.workflow.draft',JSON.stringify(draft));renderWfNode(node)};function renderWfNode(n){const el=document.createElement('div');el.className='wf-node '+(n.type==='Start'?'start':n.type.includes('Approval')||n.type==='Approval'?'approval':n.type.includes('Error')?'error':'');el.style.left=n.x+'px';el.style.top=n.y+'px';el.innerHTML=`<strong>${esc(n.type)}</strong><small>Configured node</small>`;canvas.append(el)}}
  function saveWorkflow(){const nodes=JSON.parse(sessionStorage.getItem('studio-os.workflow.draft')||'[]');if(!nodes.length)return toast('Voeg eerst minimaal één node toe');const wf={id:crypto.randomUUID?.()||Date.now().toString(36),name:`Workflow ${state.workflows.length+1}`,version:1,status:'Draft',nodes,createdAt:new Date().toISOString()};state.workflows.push(wf);audit('workflow.saved',`${wf.name} opgeslagen`,{workflowId:wf.id,nodeCount:nodes.length});toast('Workflowdefinitie opgeslagen')}
  function init(){renderNav();render();$('#menuButton').onclick=()=>$('.sidebar').classList.toggle('open');$('#addAgentButton').onclick=openAgent;$('#exportButton').onclick=exportAudit;$('#globalSearch').oninput=e=>{search=e.target.value.toLowerCase();if(route!=='agents')navigate('agents');else render()};const select=$('#agentForm select[name=team]');select.innerHTML=TEAMS.map(t=>`<option>${t}</option>`).join('');$('#agentForm').addEventListener('submit',e=>{if(e.submitter?.value==='cancel')return;e.preventDefault();registerAgent(new FormData(e.currentTarget));e.currentTarget.reset();$('#agentDialog').close()});setInterval(()=>$('#clock').textContent=new Date().toLocaleString('nl-NL',{hour:'2-digit',minute:'2-digit',second:'2-digit'})+' CET',1000)}
  init();
})();
